"""
Django settings for all_for_rest project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q#(6y6j#@e8g^i(oggwwzgnvf@b6==^rqrujbg8sl$wfoh9nwd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_dropbox_storage',
    'product',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'all_for_rest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.dropbox.DropboxStorage",
        "OPTIONS": {
            'oauth2_refresh_token': "LLQKRJQEcbMAAAAAAAAAAWp1XhrBzkHIAN_K3OHtVjJ6bpodfUUr7RmYm8jzw9pR",
            'app_secret': "84h180i1qby8ccn",
            'app_key': "z59xzchyohlzt1p",
            'root_path': '/photos/'
        },
    },
    "staticfiles": {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

DROPBOX_ACCESS_TOKEN = "sl.CBQCtP3tMBtZz_pLdgT48475k-RpU9AGHNgIFY1TRrtlE2E27G9PU26EyOUoGhEXhYTKhzRV5VSZpMLTMHc_K1pahWeCJUstsEMueZmW4wNCDwXHXwIOB8p1eJCDsm4TZEq6_2rxIKrxPt76jBTmMvk"
DROPBOX_REFRESH_TOKEN = "LLQKRJQEcbMAAAAAAAAAAWp1XhrBzkHIAN_K3OHtVjJ6bpodfUUr7RmYm8jzw9pR"
DROPBOX_APP_SECRET = "84h180i1qby8ccn"
DROPBOX_APP_KEY = "z59xzchyohlzt1p"

WSGI_APPLICATION = 'all_for_rest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "accounts.Manager"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# curl -u z59xzchyohlzt1p:84h180i1qby8ccn -d "code=FM6MTmfSYLsAAAAAAAAALnJrPFmR_UU4HjqUszFXwCk&grant_type=authorization_code" -H "Content-Type: application/x-www-form-urlencoded"  -X POST "https://api.dropboxapi.com/oauth2/token"