# Generated by Django 5.1.3 on 2024-11-22 15:24

import django_dropbox_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='photos'),
        ),
    ]
